### ISSUE TITLE
Update Tika to latest version

### ISSUE THREAD

**Issue by gggeek** [xrowgmbh/eztika#6]
Currently 1.22

**Comment by gggeek** [comment]
Tika 1.22 added to the Kaliop fork, version 1.10: https://github.com/kaliop-uk/eztika/releases/tag/1.10

**Comment by xrow** [comment]
Can you send in a pull request? Nevertheless we will not maintain tika for 5.4 anymore since all our customers will not run legacy anymore. I am happy to push updates from your end though.

**Comment by gggeek** [comment]
Hello.
I can send in a single PR with all the changes applied to the Kaliop fork so far, which would allow you to tag the official version with the same release number as the fork and minimize changes for users who already adopted the fork.

This is probably the best solution in terms of time required on your end vs. improvements for the end users, as opposed to me sending in separate PRs for all changes.

If, going forward, you plan not to spend a lot of time on this, we could as well think about transfering maintenance over to me, f.e. by adding me as committer to this repo, or possibly changing the package definition in packagist so that it points to the kaliop-uk github (I never tried that but I guess it should be possible)...

**Comment by gggeek** [comment]
PR: https://github.com/xrowgmbh/eztika/pull/8

**Comment by xrow** [comment]
Hi Gaetano,

you are Maintainer now. 

CU (soon!?) Björn

**Comment by gggeek** [comment]
Thx! :-)

Released 1.10, fixing this ticket
